# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callback_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackmanager',
            name='priority',
        ),
        migrations.AddField(
            model_name='callbackmanagerphone',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callbackmanagerschedule',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='callback_schedule.CallbackManager'),
        ),
    ]
