TWILIO_ACCOUNT_SID = '***'
TWILIO_AUTH_TOKEN = '***'
TWILIO_DEFAULT_FROM = '***'

SCHEME = 'http'
CALLBACK_CLIENT_SERIALIZER = 'rest_framework.serializers.PrimaryKeyRelatedField'
CALLBACK_MANAGER_CALL_TIMEOUT = 30
CALLBACK_CLIENT_CALL_TIMEOUT = 30

CALLBACK_INTRO_MP3 = None
