# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callback_schedule', '0002_auto_20161116_1927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('immediate', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(to='callback_schedule.CallbackManager')),
            ],
        ),
        migrations.CreateModel(
            name='CallEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('record_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid1)),
                ('manager_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callback_schedule.CallbackManagerPhone')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callback_request.CallbackRequest')),
            ],
        ),
    ]
