# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callback_schedule', '0002_auto_20161116_1927'),
        ('callback_request', '0003_auto_20161116_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackrequest',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='callentry',
            name='attempt',
        ),
        migrations.AddField(
            model_name='callentry',
            name='phone',
            field=models.ForeignKey(default='+12345', on_delete=django.db.models.deletion.CASCADE, to='callback_schedule.CallbackManagerPhone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callentry',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('canceled', 'Canceled'), ('success', 'Success'), ('failed', 'Failed')], default='waiting', max_length=32),
        ),
    ]
